// File: mux2x1Vectored.v
// Generated by MyHDL 0.11
// Date: Fri Dec 15 14:52:13 2023


`timescale 1ns/10ps

module mux2x1Vectored (
    y,
    a,
    b,
    sel
);
// Multiplexer 2x1
// y -- mux output
// a, b -- data inputs
// sel -- control input: select b if asserted, otherwise a

output [7:0] y;
reg [7:0] y;
input [7:0] a;
input [7:0] b;
input sel;




always @(a, sel, b) begin: MUX2X1VECTORED_COMB
    if ((sel == 1)) begin
        y = b;
    end
    else begin
        y = a;
    end
end

endmodule
