// File: mux2x1Scalared.v
// Generated by MyHDL 0.11
// Date: Fri Dec 15 14:51:12 2023


`timescale 1ns/10ps

module mux2x1Scalared (
    y,
    a,
    b,
    sel
);
// Multiplexer
// 
// y -- scalar data output
// a, b -- scalar data inputs
// sel -- control input: select a if asserted, otherwise b

output y;
reg y;
input a;
input b;
input sel;




always @(sel, b, a) begin: MUX2X1SCALARED_COMB
    if ((sel == 1)) begin
        y = b;
    end
    else begin
        y = a;
    end
end

endmodule
