// File: RightShiftRegister.v
// Generated by MyHDL 0.11
// Date: Fri Dec 15 14:57:39 2023


`timescale 1ns/10ps

module RightShiftRegister (
    clk,
    rst,
    data_in,
    shift_enable,
    data_out
);
// 4-bit shift register with 1-bit left shift.

input clk;
input rst;
input data_in;
input shift_enable;
output data_out;
reg data_out;

reg [3:0] reg1;



always @(reg1, shift_enable) begin: RIGHTSHIFTREGISTER_LOGIC
    if (shift_enable) begin
        data_out = reg1[0];
    end
end


always @(posedge clk) begin: RIGHTSHIFTREGISTER_SHIFT_LOGIC
    if (rst == 0) begin
        reg1 <= 0;
    end
    else begin
        if (shift_enable) begin
            reg1[3-1:0] <= reg1[4-1:1];
            reg1[3] <= data_in;
        end
    end
end

endmodule
